nextstrain/conda-base

- src/recipe.yaml
Related-to: <https://github.com/nextstrain/docker-base/pull/104>
This will fail CI until https://github.com/bioconda/bioconda-recipes/pull/37854 is merged (or an `evofr` Conda package is otherwise available).
However, I tested this branch locally by downloading and resolving using the artifacts from that PR. After download and extraction, I temporarily modified this repo's `.condarc` for testing:
```diff
diff --git a/.condarc b/.condarc
index ca52847..186994a 100644
--- a/.condarc
+++ b/.condarc
@@ -1,4 +1,5 @@
channels:
- conda-forge
- bioconda
+  - file:///home/tom/Downloads/LinuxArtifacts/packages/
channel_priority: strict
```
and then ran `./devel/build`.
> Add evofr package for forecasting work

- README.md
Having non-Nextstrain scripts mess up my conda environments in the past, I'm always careful about running things in existing environments - or even base.
In this case, all is good, no need to create an environment to be safe, so I just wanted to make this explicit.
> Add reassurance that ./devel/setup doesn't screw you

- .github/workflows/ci.yaml
Squashes noisy warnings shown on CI workflow summary pages.
See commit messages for details.
> Squash noisy CI warnings

- devel/build
This helps macOS users on arm64 chips use and produce osx-64 Conda packages instead of osx-arm64 packages (which we don't yet support).
Resolves <https://github.com/nextstrain/conda-base/issues/10>.
> dev: Set CONDA_SUBDIR during build, unless it's already set

- devel/setup
Instead of installing anaconda-client separately from the default channel, install with other packages from conda-forge.
Previous we were installing from default because the version on conda-forge was really old. Since then, the latest version of anaconda-client has been uploaded to conda-forge.
The version on conda-forge is not limited to Python <= 3.10, so we will not run into issues with Python 3.11.
An alternative to #20
> devel/setup: install anaconda-client from conda-forge

- src/recipe.yaml
pangolin and pangolearn have some tricky dependency pins that create issues. This is a known problem.
As a result, I set up separate environments for pangolin/pangolearn/usher, different from the rest of the stack.
pangolin/pangolearn is not used by any Nextstrain workflows as I'm aware, so we don't need to include them. Nextclade does the job just fine. Pangolearn now seems to require so much memory that it's not runnable on normal consumer hardware anyways (>32GB RAM).
Hence I propose to remove pangolin/pangolearn. I also pin iqtree >=2 and add some version requirements for augur/auspice/nextstrain-cli to save us from accidental downgrades when adding a new package.
Resolves #7
> Pin iqtree>=2 and remove problematic pangolin/pangolearn

- .github/workflows/ci.yaml
[ Commit message based on that of 12000a20 in nextstrain/docker-base.¹
Code changes also based on that commit, plus subsequent commits.² ]
A useful check for if new packages will break our pathogen builds.
I included all pathogen repos that already use our pathogen-repo-ci reusable workflow.  It should be minimal effort to maintain this list over time—I expect it to only grow—but perhaps in the future we will want to abstract it out into a shared list of known pathogen repos.
I don't like that we have to copy the build-args for a few of the repos here since it'll be easy for this copy to diverge from the repo's authoritative build-args, but it's necessary for now.  Over time as we work towards increased automation of pathogen builds, I think we can get rid of this build-args copy by …
> ci: Test pathogen repo CI builds with the final packages

- devel/setup
Fixes https://github.com/nextstrain/conda-base/issues/30
We can remove the pin after `anaconda-client` fixes their dependency upstream.
> devel/setup: Pin urllib3<2

- devel/download-latest
Updates `devel/download-latest` to pull the`main` labeled package with the max `version` and `build_number` so that our CI diffs of packages only compares against the latest `main` version. 
Similar to changes we made in the Nextstrain CLI (https://github.com/nextstrain/cli/pull/280).
Fixes #26
> Download latest main

- devel/build
- src/build.sh
- src/envdir
- src/recipe.yaml
This provides an `envdir` program to our Conda runtime since our other runtimes also provide this useful program and we've felt its absence.¹
Since there's no existing Conda packaging of the Python envdir distribution² we use elsewhere or any other `envdir` program AFAICT³, the particular program provided is a port I wrote long ago⁴ and still use daily on my own machines.  It's vendored into this repository and built into the Conda packages we're already producing here.  This is a quick and low-overhead solution, and we may want to switch to a packaging of the Python envdir distribution later (particularly if we want to use the Python envdir module that distribution also provides).
Resolves <https://github.com/nextstrain/conda-base/issues/35>.
¹ …
> Add envdir program

- .github/workflows/ci.yaml
This is now possible with the addition of example data in the rsv repo¹.
¹ https://github.com/nextstrain/rsv/commit/2efc4b614385a70586f0759ab0cf4600775be187
> Add nextstrain/rsv to CI

- devel/setup
Boa uses a previously deprecated and now removed API in ruamel.yaml, safe_load().  0.18.0 was the first version with its removal.
See <https://github.com/mamba-org/boa/issues/376>.
Resolves <https://github.com/nextstrain/conda-base/issues/44>.
> dev: Temporarily pin ruamel.yaml <0.18.0 to work around Boa's issue

- src/recipe.yaml
Version 8.0.0 was just released today. Pin to buy time to adjust for any breaking changes.
<https://snakemake.readthedocs.io/en/stable/project_info/history.html#id2>
> Pin Snakemake to <8

- src/recipe.yaml
Issue linked in changes. Pin to an exact version which is known to be compatible.
- https://github.com/nextstrain/augur/issues/1373
> Pin Biopython 1.81

- src/build.sh
- src/recipe.yaml
- src/target-triple
Nextclade v3 is not yet released in Bioconda. Add it as a direct download so that users of Nextstrain's Conda runtime can transition to using nextclade3.
- https://github.com/nextstrain/private/issues/97
> Add nextclade3 via direct download

- src/build.sh
See https://github.com/nextstrain/nextclade/releases/tag/3.0.0-alpha.2
Parallel change for docker-base: https://github.com/nextstrain/docker-base/pull/201
> Update `nextclade3` to alpha.2

- src/recipe.yaml
Pulp 2.8.0 breaks snakemake.
We need to pin until we upgrade snakemake to a version that is compatible with recent versions of pulp again. See https://github.com/snakemake/snakemake/issues/2607 We might need to make a similar change to docker-base
> fix: pin pulp<2.8, required by snakemake

- src/recipe.yaml
The newest version of nextclade contains a symlink to nextclade2.¹ This will eventually replaced with a symlink to nextclade3.
To continue availability of nextclade2, add a package that provides the nextclade2 binary.²
¹ <https://github.com/bioconda/bioconda-recipes/commit/c20aa93b2f346df36d26f9c00bd059ae0c1a5dda>
² <https://github.com/bioconda/bioconda-recipes/commit/b08d5c611de349a55396ecf0735ed1f3f26e8fff>
- https://github.com/nextstrain/private/issues/97
> Add nextclade2

- src/recipe.yaml
This reverts "Pin Biopython 1.81" (9fca5a848), which is no longer necessary as of Augur version 24.1.0.
<https://github.com/nextstrain/augur/releases/tag/24.1.0>
- Reverts #51
> Unpin Biopython

- .github/workflows/ci.yaml
- src/recipe.yaml
They're provided in our other runtimes (almost by happenstance, as part of the underlying OS image) and having them available in all runtimes makes it much easier to write portable programs without having to deal with GNU vs. BSD differences.
Note that typically GNU coreutils would already be available in the Conda runtime on Linux (via the host system), but not the Conda runtime on macOS (unless installed separately, e.g. via Homebrew).  So explicitly including GNU coreutils here increases consistency, isolation, and portability of the runtime.
Related-to: <https://github.com/nextstrain/ingest/issues/41>
> Provide GNU coreutils in the runtime

- src/recipe.yaml
Adds pathogen-embed to base image, so we can use its tools for analysis of reassortment in our influenza builds.
https://github.com/nextstrain/docker-base/pull/221
> Add pathogen-embed as a first-party dependency

- .github/workflows/installation.yaml
GH Action has removed macos-11 on 28 June 2024.¹
Resolves <https://github.com/nextstrain/conda-base/issues/72>
¹ <https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/#macos-11-deprecation-and-removal>
> Installation: Drop macos-11

- .github/workflows/ci.yaml
Add comments to clearly show the job using pathogen-repo-ci@v0 is for pathogen repos that do not conform to the standard pathogen repo structure. Since these are tied to a old tag of the `pathogen-repo-ci`, the job should not be expected to be updated.
Any new pathogen repos should be added to the `test-pathogen-repo-ci` job which uses the latest version of `pathogen-repo-ci`.
Prompted by https://github.com/nextstrain/conda-base/issues/83#issuecomment-2231501640
Resolves https://github.com/nextstrain/conda-base/issues/78
Related to https://github.com/nextstrain/.github/issues/84
> CI: Update test-pathogen-repo-ci

- .github/workflows/installation.yaml
This replace the brittle email notification setup with GitHub issues which should be more visible and actionable.
Closes #84
Testing done on this repo:
Testing done on personal fork repo:
- Preview: https://github.com/victorlin/conda-base/issues/9
> Surface installation failures with GitHub issues

- src/recipe.yaml
Resolves: <https://github.com/nextstrain/conda-base/issues/92>
> Revert to previous minimum glibc version of ≥2.17 instead of ≥2.28

- src/recipe.yaml
They're provided in our other runtimes (almost by happenstance, as part of the underlying OS image) and having them available in all runtimes makes it much easier to write portable programs without having to deal with GNU vs. BSD differences.
Note that typically these GNU programs would already be available in the Conda runtime on Linux (via the host system), but not the Conda runtime on macOS (unless installed separately, e.g. via Homebrew).  So explicitly including the GNU-flavored programs here increases consistency, isolation, and portability of the runtime.
These were ostensibly overlooked in "Provide GNU coreutils in the runtime" (a0b6609).
Related-to: <https://github.com/nextstrain/oropouche/pull/18#discussion_r1792991833>
> Provide GNU awk, grep, sed, and tar in the runtime

- .github/workflows/installation.yaml
This immediately verifies that the updated workflow is still valid, rather than waiting for the next scheduled run or a manual run.
Thought of this while working on #99.
> Check installation workflow upon edit

- .github/workflows/ci.yaml
- README.md
- devel/build
- devel/conda-subdir
- devel/download-latest
- devel/extract-pkg-info
- devel/setup
Build conda-base for osx-arm64 as well.
Resolves #77
> Add build for osx-arm64

- .github/workflows/installation.yaml
Remove ubuntu-20.04 since GH Actions has officially ended support for it on 2025-04-15. Add ubuntu-24.04 since it has been available for a while.
<https://github.com/actions/runner-images/issues/11101>
Following up to https://github.com/nextstrain/.github/issues/122#issuecomment-2651855979
> .github/workflows/installation: Update ubuntu runners

- .github/workflows/ci.yaml
- devel/build
- src/recipe.yaml
This is an alternative to https://github.com/nextstrain/conda-base/pull/108 that does _not_ require bumping the version for Micromamba in the Nextstrain CLI.
- pin `awscli >=2`
- pin to `_x86_64-microarch-level ==1` with `CONDA_OVERRIDE_ARCHSPEC=x86_64`
Resolves https://github.com/nextstrain/conda-base/issues/105
> Resolve hanging build for ubuntu-22.04 and macos-13 (without Micromamba bump)

- devel/build
Helpful in local development for adjusting builder options.  The build() function here already expected to receive and pass thru extra arguments but main() wasn't doing its part.
> dev: Pass arguments to ./devel/build thru to the package builder

- .github/workflows/ci.yaml
- .gitignore
- README.md
- devel/build
- devel/extract-pkg-info
- devel/setup
- devel/upload
- src/meta.yaml
conda-build became a reasonable choice ever since Conda switched to libsolv for dependency resolution (i.e. the same solver used by Mamba/Boa).  The big upside to using conda-build is that our recipe can declare:
build:
pin_depends: strict
and ditch our entire two-pass build process! \o/
Resolves: <https://github.com/nextstrain/conda-base/issues/68>
Alternatively: <https://github.com/nextstrain/conda-base/pull/113>
> dev: Use conda-build instead of boa-build

- src/meta.yaml
_Based on https://github.com/nextstrain/conda-base/pull/108 to work-around CI hanging issues_
**Update:** `bio` recipe has been fixed in bioconda with https://github.com/bioconda/bioconda-recipes/pull/55920. This PR is now only blocked on https://github.com/nextstrain/conda-base/issues/105
I wanted to add `bio` to match [docker-base](https://github.com/nextstrain/docker-base/pull/248) since I found it on [bioconda](https://bioconda.github.io/recipes/bio/README.html).
> Add bio command line tool

- src/meta.yaml
Newer versions (18.0.5…18.2.0) inexplicably hang.  See troubleshooting and conversation in Slack¹ and our open issue with upstream.²
¹ <https://bedfordlab.slack.com/archives/C7SDVPBLZ/p1747770652419989?thread_ts=1747766690.155149&cid=C7SDVPBLZ> ² <https://github.com/ncbi/datasets/issues/490>
> Pin ncbi-datasets-cli to the last working version (18.0.2) on macOS arm64

- .github/workflows/ci.yaml
This repo has been reworked to be compatible with the newer pathogen-repo-ci and thus no longer works with pathogen-repo-ci-v0.
I chose not to check the new version because it is still in progress. The only check would be on an [unstable](https://github.com/nextstrain/ebola/issues/20) and [long-running](https://github.com/nextstrain/ebola/pull/15#issuecomment-3286017943) ingest workflow, which doesn't seem useful to include here as-is.
Follow-up to https://github.com/nextstrain/ebola/pull/16#pullrequestreview-3218960692
> Remove ebola repo check
