nextstrain/conda-base

src/recipe.yaml
Related to https://github.com/nextstrain/docker-base/pull/110
=> Add NCBI Datasets CLI

.github/workflows/ci.release.md, .github/workflows/ci.yaml, devel/_common, devel/build, devel/conda-subdir, devel/diff-pkgs, devel/download-latest, devel/extract-pkg-info, devel/setup
See commit messages for details.
See also GitHub Actions' documentation on step summaries.¹
¹ https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary
=> dev: Add summary information to CI runs

src/recipe.yaml
Analogous to https://github.com/nextstrain/docker-base/pull/146
=> Add pango_aliasor

devel/setup
This is a follow-up to bc2dbd5acb85440ec9cab1da90c2120838f58ea0 now that the latest version of anaconda-client supports latest urllib3 ¹.
¹ https://github.com/Anaconda-Platform/anaconda-client/blob/2a3ce88c8c37a2ea4276a0135e707e51e1015b66/CHANGELOG.md#1120---2023-07-18
- #30
=> Unpin urllib3, pin anaconda-client>=1.12.0

.github/workflows/ci.yaml
- https://github.com/nextstrain/mpox/issues/168
- https://github.com/nextstrain/.github/issues/63
=> CI: Rename and disable mpox build

devel/setup
Updating pins for old and new issues. See commit messages.
- Follow-up to 8cdf5a7948a07209876609487b000b2619941376
- https://github.com/mamba-org/boa/issues/388
=> Fix setup env

.github/workflows/ci.yaml
Repurpose and move related comment + disabling of mpox to the bottom of the pathogen list.
- https://github.com/nextstrain/.github/issues/63
=> Temporarily disable zika CI

.github/workflows/installation.yaml
This is our daily "does it still install?" check.
=> dev: Test installation on macOS 13 and 14 too

.github/workflows/ci.yaml
Mirrors the change in avian-flu's CI.
- https://github.com/nextstrain/avian-flu/pull/17
=> Reference new CI target

.github/workflows/installation.yaml
Reflects our current best understanding of how notifications for failed scheduled workflow runs work.¹
¹ <https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1720504387401829?thread_ts=1720210165.766899&cid=C01LCTT7JNN>
=> dev: Add comment about updating the installation workflow's schedule

.github/workflows/ci.yaml
**Status: Blocked, awaiting merge of <https://github.com/nextstrain/avian-flu/pull/72>**
Mirrors the change in [avian-flu's CI](https://github.com/nextstrain/avian-flu/pull/72)
=> Update avian-flu CI

.github/workflows/ci.yaml
Based on https://github.com/nextstrain/conda-base/pull/85
Blocked on merge of https://github.com/nextstrain/lassa/pull/8
=> Update lassa CI

src/recipe.yaml
Ideally this would have been added before or as Augur 25.3.0—the first version to include `augur merge`—was packaged into this runtime, but I plain forgot.
=> Add the SQLite CLI for `augur merge`

.github/workflows/ci.yaml, .github/workflows/installation.yaml
Keeping things up to date.
- Closes #95
- Closes nextstrain/.github#115
=> Update macOS runners

.github/workflows/ci.yaml
Part of https://github.com/nextstrain/conda-base/issues/101
=> CI: add new pathogens to `test-pathogen-repo-ci`

.github/workflows/ci.yaml
Follow up on <https://github.com/nextstrain/avian-flu/pull/103>
Part of https://github.com/nextstrain/public/issues/20
=> CI/test-pathogen-repo-ci-v0: fix avian-flu build-args

.github/workflows/ci.yaml
=> Update mumps CI

src/meta.yaml
Newer versions support glibc 2.17.
Closes #119
- ~[ ] Update changelog~ no changelog here
=> Allow newer versions of c-ares

src/meta.yaml
Matching change in docker-base
https://github.com/nextstrain/docker-base/pull/261
=> Update IQ-TREE to version 3

.github/workflows/ci.yaml
The rsv repo now has a CI-specific config file.
https://github.com/nextstrain/rsv/issues/104
=> CI: Add build args for rsv CI
